version: "3.9"
  
services:
  dockerproxy:
    container_name: docker-proxy
    environment:
      - CONTAINERS=1
      - EVENTS=1
      - INFO=1
      - LOG_LEVEL=info
      - PING=1
      - VERSION=1
      - AUTH=0
      - SECRETS=0
      - POST=1
    image: tecnativa/docker-socket-proxy:latest
    ports:
      - "10.0.0.53:2375:2375"
      
    networks:
      - proxy
      
    privileged: true
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      

networks:
  proxy:
    external: true
    name: proxy
                                     