version: '3.3'

services:
  agent:
    image: portainer/agent:2.18.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - traefik-public
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
  portainer:
    image: portainer/portainer-ee:2.18.1
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    volumes:
      - "/docker-volume/portainer/portainer_data:/data"

    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.http.routers.portainer.entrypoints=web-secure"
        - "traefik.http.routers.portainer.rule=Host(`node1-catedral.eulabs.app.br`)"
        - "traefik.http.routers.portainer.tls.domains[0].main=*.eulabs.app.br"
        - "traefik.http.routers.portainer.service=portainer"
        - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"


networks:
  traefik-public:
    external: true
    driver: overlay
    attachable: true

